#%RAML 1.0
title: jenkins-test2
version: 1.0
mediaType: 
- application/json
- application/xml
protocols:
  - HTTP
  - HTTPS

/jenkinstest2:
  post:
    body:
      application/json:
    responses:
      200:
        body:
          application/xml:
            